name: tyba_test
description: "A flutter test for Tyba"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.3.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  form_builder_validators: ^10.0.1
  go_router: ^14.1.4
  http: ^1.2.1
  logger: ^2.3.0
  recase: ^4.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
