part of 'ui.dart';

/// Constant gap widths
const gapW2 = SizedBox(width: UISize.p2);
const gapW4 = SizedBox(width: UISize.p4);
const gapW6 = SizedBox(width: UISize.p6);
const gapW8 = SizedBox(width: UISize.p8);
const gapW12 = SizedBox(width: UISize.p12);
const gapW16 = SizedBox(width: UISize.p16);
const gapW20 = SizedBox(width: UISize.p20);
const gapW24 = SizedBox(width: UISize.p24);
const gapW28 = SizedBox(width: UISize.p28);
const gapW32 = SizedBox(width: UISize.p32);
const gapW40 = SizedBox(width: UISize.p40);
const gapW48 = SizedBox(width: UISize.p48);
const gapW56 = SizedBox(width: UISize.p56);
const gapW64 = SizedBox(width: UISize.p64);
const gapW72 = SizedBox(width: UISize.p72);
const gapW80 = SizedBox(width: UISize.p80);
const gapW88 = SizedBox(width: UISize.p88);
const gapW96 = SizedBox(width: UISize.p96);
const gapW104 = SizedBox(width: UISize.p104);
const gapW112 = SizedBox(width: UISize.p112);
const gapW128 = SizedBox(width: UISize.p128);
const gapW136 = SizedBox(width: UISize.p136);
const gapW144 = SizedBox(width: UISize.p144);

/// Constant gap heights
const gapH2 = SizedBox(height: UISize.p2);
const gapH4 = SizedBox(height: UISize.p4);
const gapH6 = SizedBox(height: UISize.p6);
const gapH8 = SizedBox(height: UISize.p8);
const gapH12 = SizedBox(height: UISize.p12);
const gapH16 = SizedBox(height: UISize.p16);
const gapH20 = SizedBox(height: UISize.p20);
const gapH24 = SizedBox(height: UISize.p24);
const gapH28 = SizedBox(height: UISize.p28);
const gapH32 = SizedBox(height: UISize.p32);
const gapH40 = SizedBox(height: UISize.p40);
const gapH48 = SizedBox(height: UISize.p48);
const gapH56 = SizedBox(height: UISize.p56);
const gapH64 = SizedBox(height: UISize.p64);
const gapH72 = SizedBox(height: UISize.p72);
const gapH80 = SizedBox(height: UISize.p80);
const gapH88 = SizedBox(height: UISize.p88);
const gapH96 = SizedBox(height: UISize.p96);
const gapH104 = SizedBox(height: UISize.p104);
const gapH112 = SizedBox(height: UISize.p112);
const gapH128 = SizedBox(height: UISize.p128);
const gapH136 = SizedBox(height: UISize.p136);
const gapH144 = SizedBox(height: UISize.p144);
